version: '3.8'

services:
  webboard:
    build: ./
    container_name: webboard-service
    ports:
      - '4001:4000'
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/webboard
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webboard
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
